# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/apps/data-service'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/apps/frontend'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/apps/redis-sdk'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/apps/wtw'
    schedule:
      interval: 'daily'
