version: '3.7'
services:
  redis-base:
    image: redislabs/rejson
    hostname: redis-redisjson
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
