version: '3.7'
services:
  redis-base:
    image: redislabs/rejson
    hostname: redis-redisjson
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - $PWD/.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - cache:/data
    restart: always
