version: '3.7'
services:
  redis:
    extends:
      file: common-services.yml
      service: redis-base
  data-service:
    build:
      context: .
      dockerfile: ./apps/data-service/Dockerfile
    restart: always
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always