version: '3.7'
services:
  redis:
    extends:
      file: common-services.yml
      service: redis-base
    networks:
      - webnet
  data-service:
    image: ${REGISTRY_HOST}/wmca/data-service:${GITHUB_SHA_SHORT}
    build:
      context: .
      dockerfile: ./apps/data-service/Dockerfile
    depends_on:
      - redis
    ports:
      - '${CRON_PORT}:${CRON_PORT}'
    networks:
      - webnet
    restart: always
  api:
    image: ${REGISTRY_HOST}/wmca/api:${GITHUB_SHA_SHORT}
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - webnet
    restart: always
networks:
  webnet:
