#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - ubuntu: [root, sys]
  - wmca

packages:
  - git
  - nginx
  - certbot
  - python3-certbot-nginx

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: wmca
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh-authorized-keys:
      - ${pub_key}

runcmd:
  - /usr/bin/git clone https://github.com/dills122/where-my-cage-at.git app-src
  - sudo ufw allow 'Nginx Full'
  - sudo ufw deny 6379 # Lockdown redis port from the outside world
  - sudo wget -O /usr/local/bin/ufw-docker https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
  - sudo chmod +x /usr/local/bin/ufw-docker
  - sudo ufw-docker install
  - sudo systemctl restart ufw
  - /usr/bin/bash ./app-src/scripts/certbot.sh
  - /usr/bin/bash ./app-src/scripts/deploy.sh
  - /usr/bin/docker update --restart unless-stopped $(docker ps -q)

final_message: 'The system is finally up, after $UPTIME seconds'
