name: CI Job

on:
  pull_request:
    types: [synchronize, opened, reopened]
jobs:
  eslint_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js lint
  prettier_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js prettier
  automerge:
    runs-on: ubuntu-latest
    needs: [eslint_linter_job, prettier_linter_job]
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
