name: Publish Docker Images to DO

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    tags:
      - 'v*'
    paths:
      - apps/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2
env:
  REGISTRY_HOST: 'registry.digitalocean.com/wmca'
  FRONTEND_IMAGE_NAME: 'ang-frontend-builder'
  CLUSTER_IMAGE_NAME: 'cluster-services'

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set GH_SHA for versioning images
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Build frontend build image
        run: docker build -t $(echo $REGISTRY_HOST)/$(echo $FRONTEND_IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) -f AngBuildDockerfile .

      - name: Build service images
        run: docker-compose build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      # Make sure to cleanup the services containers, frontend build should get cleaned up during deployment
      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $CLUSTER_IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $CLUSTER_IMAGE_NAME) $(doctl registry repository list-tags $(echo $CLUSTER_IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push cluster service images to DigitalOcean Container Registry
        run: docker-compose push

      - name: Push frontend build image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY_HOST)/$(echo $FRONTEND_IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  # TODO needs to still be worked on
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: FRONTEND_IMAGE_NAME,CLUSTER_IMAGE_NAME,REGISTRY_HOST,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          script: |
            # Login to registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            # Build frontend & setup frontend
            sudo docker create -ti --name dummy $(echo $FRONTEND_IMAGE_NAME) bash
            sudo docker cp dummy:/tmp/apps/frontend/dist/frontend/. /var/www/prod
            sudo docker rm -f dummy
            # Stop running container
            docker-compose down --rmi all
            # Remove old container
            docker rm $(echo $CLUSTER_IMAGE_NAME)
            # Start up cluster
            docker-compose up -d
